### ISSUE TITLE
ML2 TA feedback

### ISSUE THREAD

**Issue by afshinamini** [UBC-MDS/Mental-Health-in-Tech-Dashboard#36]
Hi Folks,

Great Job! It's easy to work with and informative. Few comments:
- On pie charts I likes the double clicking module but it doesn't do anything extra as it isolates one variable which covers 100% of the chart.
- on second row of charts from the top: "Does your mental health..." 
 1- arrange the order of legend to match the chart
 2- It would be great it you could make both charts to have the same scale for "number of responses". It would make comparison easier.

Cheers,
Afshin

**Comment by fatse** [comment]
Hi @afshinamini 

Thank you very much for your valuable feedback on our dashboard app.
Your suggestions seem reasonable and we will address them in [Milestone 4.](https://github.com/UBC-MDS/Mental-Health-in-Tech-Dashboard-R/issues/11)

As for the first point, we need to investigate a little and see if we can change the default behavior of plotly (since what you pointed out is the default behavior) and if yes, how much effort it will take to make those adjustments. Note that we also let Joel know about the default behavior of _plotly donut charts_ and he as well suggested what we stated in this paragraph regarding the first point in your feedback. 

With sincere appreciation,
Fatime

**Comment by d-sel** [comment]
Am closing the issue as the feedback has been addressed in Milestone 4.

**Comment by fatse** [comment]
Providing the link of the PR that addressed the issues listed from the TA above:

1. Disable double click on donut charts: https://github.com/UBC-MDS/Mental-Health-in-Tech-Dashboard/pull/48
2. Second row of charts from the top: https://github.com/UBC-MDS/Mental-Health-in-Tech-Dashboard/pull/40
