### ISSUE TITLE
2. Proposal - Section 3: Research questions and usage scenarios

### ISSUE THREAD

**Issue by mikelynch416** [UBC-MDS/Mental-Health-in-Tech-Dashboard#4]
For this it can be helpful to create a brief persona description of a member in your intended target audience and write small user story for what they might do with your app. User stories are typically written in a narrative style and include the specific context of usage, tasks associated with that use context, and a hypothetical walkthrough of how the user would accomplish those tasks with your app. If you are using a Kaggle dataset, you may use their "Overview (inspiration)" to create your usage scenario.

An example usage scenario with tasks (tasks are indicated in brackets, i.e. [task], and are optional to include)

Mary is a policy maker with the Canadian Ministry of Health and she wants to understand what factors lead to missed appointments in order to devise an intervention that improves attendance numbers. She wants to be able to [explore] a dataset in order to [compare] the effect of different variables on absenteeism and [identify] the most relevant variables around which to frame her intervention policy. When Mary logs on to the "Missed Appointments app", she will see an overview of all the available variables in her dataset, according to the number of people that did or did not show up to their medical appointment. She can filter out variables for head-to-head comparisons, and/or rank patients according to their predicted probability of missing an appointment. When she does so, Mary may notice that "physical disability" appears to be a strong predictor missing appointments, and in fact patients with a physical disability also have the largest number of missed appointments. She hypothesizes that patients with a physical disability could be having a hard time finding transportation to their appointments, and decides she needs to conduct a follow-on study since transportation information is not captured in her current dataset.

Note that in the above example, "physical disability" being an important variable is fictional. You don't need to conduct an analysis of your data to figure out what is important or not. Instead, estimate what someone might find, and how they may use this information.

**Comment by mikelynch416** [comment]
**Example Usage Scenario**
Mary is a policy maker in HR for a large tech company and she wants to understand what factors affect the mental health of tech workers so that she can create policies that will improve productivity by reducing the likelihood of employees developing mental health conditions that affect their work. 

She wants to be able to [explore] a dataset in order to [compare] the effect of different variables on the rate at which employees develop mental health conditions that affect their work (called "work_interfere" in the dataset) and [identify] the most relevant variables around which to frame her new policies. 

When Mary logs on to the "Mental Health in Tech Workers app", she will see an overview of all the available variables in the dataset, according to how each variable affects the work_interfere rate. 

She can then use her domain expert knowledge to [filter] out variables which would be difficult to craft HR policies around (ex. in Canada an employer cannot make policies which discriminate on the basis of family history of mental illness [citation: https://laws-lois.justice.gc.ca/eng/acts/h-6/fulltext.html#:~:text=3%20(1)%20For%20all%20purposes,which%20a%20pardon%20has%20been], so this variable will probably not be relevant for her usage). She can then [rank] the remaining variables according to metrics like how correlated they are to the work_interfere rate. When she does this, Mary may notice that the "seek_help" variable, which corresponds to the survey question "Does your employer provide resources to learn more about mental health issues and how to seek help?", appears to be a strongly negatively correlated to the development of mental health conditions affecting employment. She notes this correlation and hypothesizes that introducing a policy to provide resources for employees seeking help with regards to mental health will reduce the work_interfere rate at her company, and decides she needs to conduct a follow-on study to test this hypothesis.

**Research Questions**
From the usage scenario some example research questions we would like our dashboard to be able to answer were identified, including: 
- Are there notable relationships between variables in the dataset? Do these relationships inspire ideas for policy changes among HR domain experts? 
- What variables correlate most closely to the work_interfere variable?
- Can the work_interfere variable be consistently predicted using a subset of the other variables in the dataset? What are the most important variables for doing this?

**Comment by d-sel** [comment]
**Section 1: Motivation and Purpose**

Our role: Data scientist consultancy firm

Target audience: HR professionals in large companies

Mental health issues can be costly to organizations due to lost productivity, absences and even disability. The World Health Organization estimates that half of all disability worldwide is due to mental health and that 200 million workdays are lost annually due to absenteeism relating to mental health in the United States (Harnois, Gaston, Gabriel, Phyllis, World Health Organization & International Labour Organisation. (2000). Mental health and work : impact, issues and good practices. World Health Organization. https://apps.who.int/iris/handle/10665/42346). Although HR departments implement processes and cultivate workplace culture so as to encourage good mental health, it is often unclear whether these policies do in fact make a difference. If these policy makers could explore which factors are indicators of mental health and what policies are effective in helping employees seek out help, such as providing benefits or providing accessible options, the organization can take a smarter approach to policy implementation. The benefits of reducing mental health could lead to decreased absenteeism, improved employee morale as well providing the organization with a positive reputation for being a good place to work.

To address these issues, we propose a dashboard which would be used by HR professionals who are in charge of setting HR policy in organizations to visually explore a survey dataset of mental health attitudes from tech workers across the globe to identify potential connections that may help with policy setting. The dashboard will allow filtering between responses for those who indicate that they do have a mental health issue versus those that do not so that differences between responses can be compared.
